Assignments/array hofs
bhs-intro-to-programming/Eliass-m pull request #46
Opened 2023-03-01 23:31 UTC by Eliass-m

2023-03-02 00:55 UTC, gigamonkey requested changes
Good start. Keep going.

2023-03-02 00:55 UTC, gigamonkey commented on assignments/array-hofs/code.js
> +  return array.filter((n) => n / 100 > 1)
dunno which of the three of you came up with this. it works but it's a funny way to write `n > 100`

2023-03-02 22:38 UTC, Eliass-m commented on assignments/array-hofs/code.js
> +  return array.filter((n) => n / 100 > 1)
theo

2023-03-03 01:11 UTC, gigamonkey requested changes
Almost there! Just one to go. Everything else looks fine.

2023-03-05 21:19 UTC, gigamonkey approved these changes
Looks good.

2023-03-07 16:43 UTC, gigamonkey approved these changes
The ones you've done look good.

2023-03-07 22:37 UTC, merged